In [1]:
import torch

## create tensor

### 简单地生成tensor

In [2]:
x = torch.arange(12) # create for range
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [5]:
x.numel() # num of elments

12

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros((2, 3, 4)) # create all zero

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2, 3, 4)) # create all one

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
torch.tensor([[1,2,3], [2,3,4], [3,4,5]]) # create specific tensor

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

### tensor->tensor

In [17]:
# cat: 多个tensor联结在一起

X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1,2,3,4], [3,4,5,6]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)
# dim: 按照哪个维度的方向拼接

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 3.,  4.,  5.,  6.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  3.,  4.,  5.,  6.]]))

## calculation

### 标准计算

In [13]:
# 标准计算: 按元素一一对应计算

x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([2, 3, 3, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([3, 5, 6, 6]),
 tensor([-1, -1,  0,  2]),
 tensor([2, 6, 9, 8]),
 tensor([0.5000, 0.6667, 1.0000, 2.0000]),
 tensor([ 1,  8, 27, 16]))

In [20]:
# ERROR: 一维时size必须一致

x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([2, 3, 3])
x+y, x-y, x*y, x/y, x**y

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

#### broadcasting mechanism

In [22]:
# 维度一致，size不同，会触发广播机制


a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
a + b # 两个tensor。首先维度一样，都是2维。a复制成3*2，b复制成3*2

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 其他计算

In [18]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
x.sum() # 一个元素的标量

tensor(66.)

### 取特定的元素

In [25]:
X = torch.tensor([[1,2,3,4], [2,3,4,5], [1,1,1,2]])
X, X[1]

(tensor([[1, 2, 3, 4],
         [2, 3, 4, 5],
         [1, 1, 1, 2]]),
 tensor([2, 3, 4, 5]))

In [26]:
X[1,2]

tensor(4)

In [27]:
X[1:2]

tensor([[2, 3, 4, 5]])

In [30]:
X[0:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 1,  1,  1,  2]])

## 内存

In [33]:
X = torch.tensor([[1, 2, 3], [1,1,1]])
Y = torch.tensor([[1,1,1], [2,2,2]])
before = id(X)
X = X+Y
id(X) == before

False

不重新分配内存，可减少内存开销

In [35]:
before = id(X)
X += Y
id(X) == before

True

In [36]:
before = id(X)
X[:] = X+Y
id(X) == before

True

## Numpy

In [37]:
A = X.numpy() # ->numpy.ndarray类型
B = torch.tensor(A) # ->torch.tensor类型
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [38]:
# 将大小为1的张量转化为Python标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)