In [1]:
import torch
from torch import nn
from torch.nn import functional as F

# 存储/读取 一个张量
x = torch.arange(4)
torch.save(x, 'x-files')

x2 = torch.load('x-files')
x2

tensor([0, 1, 2, 3])

In [2]:
# 存储/读取 一个张量列表
y = torch.zeros(4)
torch.save([x, y], 'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [4]:
# 存储/读取 从字符串映射到张量的字典
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

加载和保存模型参数

In [5]:
# pytorch 一般不存储网络模型，存储参数
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [6]:
# 将模型的参数存储为一个文件
torch.save(net.state_dict(), 'mlp.params')

In [9]:
# 实例化原始MLP模型的一个备份
clone = MLP() 
# 读取文件存储的参数
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [10]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])