求和

In [1]:
# sum整体求和

import torch
A = torch.arange(2*20, dtype=torch.float32).reshape(2,5,4)
A, A.sum()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor(780.))

In [2]:
# 指定轴求和

A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [3]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [4]:
A_sum_01 = A.sum(axis=[0,1])
A_sum_01, A_sum_01.shape

(tensor([180., 190., 200., 210.]), torch.Size([4]))

其他计算

In [5]:
# 均值
A.mean(), A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [8]:
# 求和但是保持维度
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [9]:
# 累加求和
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [10]:
# 向量的点积

x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [11]:
torch.sum(x*y)

tensor(6.)

In [13]:
# 矩阵*向量 Ax
# torch.mv(A, x) # matrix-vector

A = torch.arange(20, dtype=torch.float32).reshape(5,4)
A.shape, x.shape, torch.mv(A, x) # matrix-vector

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [14]:
# torch.mm(A, B) # matrix-matrix
B = torch.ones(4,3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [15]:
# 范数

# 向量的L2范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [16]:
# 向量的L1范数
torch.abs(u).sum()

tensor(7.)

In [17]:
# 矩阵的F范数（矩阵元素平方和的平方根）
torch.norm(torch.ones((4,9)))

tensor(6.)